spring.application.name=rental-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
server.port=0
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.retry.retry-aspect-order=2
resilience4j.retry.instances.vehicle-service.max-attempts=2
resilience4j.retry.instances.vehicle-service.wait-duration=5000